# Generated by Django 3.2.9 on 2022-01-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staffmas',
            fields=[
                ('empid', models.AutoField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50)),
                ('pmiscode', models.IntegerField()),
                ('empdob', models.DateField()),
                ('empquali', models.CharField(max_length=50)),
                ('empmob', models.IntegerField()),
                ('emppic', models.ImageField(upload_to='staffpic')),
                ('empemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
