# Generated by Django 3.2.9 on 2022-01-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='desigmas',
            fields=[
                ('desigcd', models.AutoField(primary_key=True, serialize=False)),
                ('deisgnm', models.CharField(max_length=50)),
            ],
        ),
    ]
