# Generated by Django 3.2.9 on 2022-01-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_staffmas_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujcname', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='staffmas',
            name='empdoj',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmas',
            name='sntyno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
