# Generated by Django 3.2.9 on 2022-01-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220105_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmas',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.subjmas'),
            preserve_default=False,
        ),
    ]
