# Generated by Django 3.2.9 on 2022-01-05 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_staffmas_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmas',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.desigmas'),
        ),
        migrations.AlterField(
            model_name='staffmas',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subjmas'),
        ),
    ]
