# Generated by Django 3.2.9 on 2022-01-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220105_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmas',
            name='emppic',
            field=models.ImageField(upload_to='staffpic/'),
        ),
    ]
