# Generated by Django 3.2.9 on 2022-01-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_staffmas_emppic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmas',
            name='emppic',
            field=models.ImageField(upload_to='staffpic'),
        ),
    ]
