# Generated by Django 3.2.9 on 2022-01-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_staffmas_emppic'),
    ]

    operations = [
        migrations.CreateModel(
            name='catmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='staffmas',
            name='empcat',
            field=models.ForeignKey(blank=True,null=True, on_delete=django.db.models.deletion.CASCADE, to='home.catmas'),
            preserve_default=False,
        ),
    ]
