# Generated by Django 3.2.9 on 2022-01-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220106_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmas',
            name='empcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.catmas'),
        ),
    ]
