# Generated by Django 3.2.9 on 2022-01-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_staffmas_empsex'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankifsc', models.CharField(default=False, max_length=11)),
                ('bnkbranchnm', models.CharField(default=False, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='classmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasdesc', models.CharField(max_length=20, unique=True)),
                ('classlvl', models.CharField(default=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='disttmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disttcd', models.CharField(default=False, max_length=2)),
                ('disttnm', models.CharField(default=False, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='panchayatmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancd', models.CharField(default=False, max_length=2)),
                ('panname', models.CharField(default=False, max_length=20)),
                ('disttcd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disttmas')),
            ],
        ),
        migrations.CreateModel(
            name='pomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincd', models.IntegerField()),
                ('ponmame', models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='schoolmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udise', models.IntegerField()),
                ('schoolcoe', models.IntegerField()),
                ('Schoolnm', models.CharField(max_length=50)),
                ('schooladdress', models.CharField(default=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='statemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statenm', models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='staffmas',
            name='empsex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Feamle'), ('O', 'Other/लागू नहीं')], default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='tehmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tehcd', models.CharField(default=False, max_length=2)),
                ('tehname', models.CharField(default=False, max_length=25)),
                ('disttcd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disttmas')),
                ('stcod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.statemas')),
            ],
        ),
        migrations.CreateModel(
            name='studentbasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdname', models.CharField(default=False, max_length=25)),
                ('stfname', models.CharField(default=False, max_length=25)),
                ('stmname', models.CharField(default=False, max_length=25)),
                ('strelig', models.CharField(choices=[('H', 'Hindu'), ('M', 'Muslim'), ('S', 'Sikh'), ('C', 'Christian')], default='H', max_length=1)),
                ('stcat', models.CharField(choices=[('G', 'General'), ('O', 'OBC'), ('S', 'SC'), ('T', 'ST'), ('N', 'Not Applicable')], default='G', max_length=1)),
                ('stsex', models.CharField(choices=[('M', 'Male'), ('F', 'Feamle'), ('O', 'Other')], default='M', max_length=1)),
                ('stdob', models.DateField()),
                ('stdoa', models.DateField()),
                ('Stadmno', models.IntegerField()),
                ('stadyear', models.IntegerField()),
                ('stdacct', models.IntegerField()),
                ('stdmob', models.IntegerField()),
                ('stduid', models.IntegerField()),
                ('stvillg', models.CharField(default=False, max_length=25)),
                ('stsatus', models.CharField(default=False, max_length=1)),
                ('Stteh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tehmas')),
                ('stbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bankmas')),
                ('stclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.classmas')),
                ('stdistt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.disttmas')),
                ('stpanch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.panchayatmas')),
                ('stpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pomas')),
            ],
        ),
        migrations.AddField(
            model_name='panchayatmas',
            name='stcd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.statemas'),
        ),
        migrations.AddField(
            model_name='panchayatmas',
            name='tehcd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tehmas'),
        ),
        migrations.AddField(
            model_name='disttmas',
            name='scode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.statemas'),
        ),
    ]
