# Generated by Django 3.2.9 on 2022-01-12 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220110_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmas',
            name='empcst',
            field=models.CharField(choices=[('G', 'General'), ('O', 'OBC'), ('S', 'SC'), ('T', 'ST'), ('N', 'Not Applicable')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='staffmas',
            name='schoolcd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.schoolmas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffmas',
            name='empcat',
            field=models.CharField(choices=[('T', 'Teaching Staff'), ('N', 'Non Teaching Staff'), ('S', 'SMC')], default='T', max_length=1),
        ),
    ]
