# Generated by Django 3.2.9 on 2022-01-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220113_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tehmas',
            name='tehcd',
        ),
    ]
