# Generated by Django 3.2.9 on 2022-01-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_tehmas_tehcd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panchayatmas',
            name='pancd',
        ),
    ]
