# Generated by Django 4.0.1 on 2022-01-30 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_disttmas_disttcd'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomas',
            name='distcd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.disttmas'),
            preserve_default=False,
        ),
    ]
