# Generated by Django 4.0.1 on 2022-01-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_pomas_distcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmas',
            name='classlvl',
            field=models.CharField(choices=[('E', 'Elementary'), ('H', 'Higher'), ('S', 'Secondary')], default='S', max_length=1),
        ),
    ]
