# Generated by Django 4.0.1 on 2022-02-10 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_classsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='exammas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exmtype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='studentclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adyear', models.CharField(max_length=4, null=True)),
                ('admno', models.IntegerField(null=True)),
                ('admdate', models.DateField(null=True)),
                ('rollno', models.IntegerField(null=True)),
                ('appdate', models.DateField(null=True)),
                ('sesyear', models.CharField(max_length=4)),
                ('examrno', models.IntegerField()),
                ('mo', models.IntegerField(default=0)),
                ('mm', models.IntegerField(default=0)),
                ('clstat', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail'), ('L', 'SLC'), ('A', 'Admitted'), ('E', 'Pending')], default='E', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentbasic',
            name='Stadmno',
        ),
        migrations.RemoveField(
            model_name='studentbasic',
            name='stadyear',
        ),
        migrations.RemoveField(
            model_name='studentbasic',
            name='stclass',
        ),
        migrations.RemoveField(
            model_name='studentbasic',
            name='stdoa',
        ),
        migrations.AddField(
            model_name='studentbasic',
            name='stblood',
            field=models.CharField(choices=[('A', 'A+'), ('A1', 'A-'), ('B', 'B+'), ('B1', 'B-'), ('O', 'O+'), ('O1', 'O-'), ('AB', 'AB+'), ('AB1', 'AB-'), ('Z', 'Not Known')], default='Z', max_length=3),
        ),
        migrations.AddField(
            model_name='studentbasic',
            name='stdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentbasic',
            name='sthrtc',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='studentbasic',
            name='stpic',
            field=models.ImageField(null=True, upload_to='staffpic'),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stdname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stfname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stmname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stsatus',
            field=models.CharField(choices=[('A', 'Admitted'), ('E', 'Pending'), ('L', 'SLC')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='stvillg',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='studentsubj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmo', models.IntegerField()),
                ('amo', models.IntegerField()),
                ('pmo', models.IntegerField()),
                ('subjresult', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail')], max_length=1, null=True)),
                ('examcd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.exammas')),
                ('stuclid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentclass')),
                ('subjcd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subjmas')),
            ],
        ),
        migrations.AddField(
            model_name='studentclass',
            name='appid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentbasic'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='classcd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.classmas'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.schoolmas'),
        ),
    ]
